sudo: false
language: python
matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6-dev
      env: TOXENV=py36-dev
    - python: nightly
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=lint
  allow_failures:
    - env: TOXENV=py36-dev
    - env: TOXENV=py37
install: pip install tox
# TODO: https://github.com/tox-dev/tox/issues/149
script: tox --recreate
cache:
  directories:
    - .tox
    - $HOME/.cache/pip
